#pragma once

#define ERROR_NOERROR          1
#define ERROR_FILE_DONT_EXIST  100
#define ERROR_FILEINTEGRITY    101
#define ERROR_CREATEFILE       102
#define ERROR_INVALIDFILE      103
#define ERROR_FINGERPRINT       150
#define ERROR_RETRIEVING_FINGERPRINt    151

